name: 'setup-rust'
author: 'puniyu'
description: '设置Rust作'
branding:
  icon: activity
  color: purple

inputs:
  toolchain:
    description: Rust toolchain specification
    required: false
  components:
    required: false
    type: string
    description: space separated Rust components
  target:
    required: false
    type: string
    description: target triple to install
  tools:
    required: false
    type: string
    description: comma separated Cargo tools
  save-cache:
    default: false
    required: false
    type: boolean
    description: whether to save cache
  prefix-key:
    required: false
    type: string
    description: cache key prefix

runs:
  using: 'composite'
  steps:
    - name: Check File
      id: check_file
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3
      with:
        files: "rust-toolchain.toml"

    - name: Get Version from Toolchain File
      id: get_version
      uses: SebRollen/toml-action@b1b3628f55fc3a28208d4203ada8b737e9687876 # v1.2.0
      if: steps.check_file.outputs.files_exists == 'true'
      with:
        file: 'rust-toolchain.toml'
        field: 'toolchain.channel'

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain || (steps.get_version.outputs.value || 'stable') }}

    - name: Add Target
      shell: bash
      if: ${{ inputs.target }}
      run: rustup target add ${{ inputs.target }}

    - name: Add Components
      shell: bash
      if: ${{ inputs.components }}
      run: rustup component add ${{ inputs.components }}

    - name: Install Tools
      uses: taiki-e/install-action@3575e532701a5fc614b0c842e4119af4cc5fd16d # v2
      if: ${{ inputs.tools }}
      with:
        tool: ${{ inputs.tools }}

    - name: Cache
      uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
      if: ${{ inputs.save-cache == 'true' }}
      with:
        prefix-key: ${{ inputs.prefix-key || '' }}
        save-if: ${{ inputs.save-cache == 'true' }}