name: 'setup-rust'
author: 'puniyu'
description: '设置Rust作'


inputs:
  toolchain:
    description: Rust toolchain specification
    required: false
  components:
    required: false
    type: string
    description: space separated Rust components
  target:
    required: false
    type: string
    description: target triple to install
  tools:
    required: false
    type: string
    description: comma separated Cargo tools
  cache:
    default: false
    required: false
    type: boolean
    description: whether to save cache
  prefix-key:
    required: false
    type: string
    description: cache key prefix

runs:
  using: 'composite'
  steps:
    - name: Check File
      id: check_file
      uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
      with:
        files: "rust-toolchain.toml"

    - name: Get Version from Toolchain File
      id: get_version
      uses: SebRollen/toml-action@b1b3628f55fc3a28208d4203ada8b737e9687876 # v1.2.0
      if: steps.check_file.outputs.files_exists == 'true'
      with:
        file: 'rust-toolchain.toml'
        field: 'toolchain.channel'

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
      with:
        toolchain: ${{ inputs.toolchain || (steps.get_version.outputs.value || 'stable') }}

    - name: Add Target
      shell: bash
      if: ${{ inputs.target }}
      run: rustup target add ${{ inputs.target }}

    - name: Add Components
      shell: bash
      if: ${{ inputs.components }}
      run: rustup component add ${{ inputs.components }}

    - name: Install Tools
      uses: taiki-e/install-action@6c6fd71fe4fb72c3697d269963d0e15df8adedad # v2.85.10
      if: ${{ inputs.tools }}
      with:
        tool: ${{ inputs.tools }}

    - name: Cache
      uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
      if: ${{ inputs.cache == 'true' }}
      with:
        prefix-key: ${{ inputs.prefix-key || '' }}
        save-if: ${{ inputs.cache == 'true' }}