name: 'setup-rust'
author: 'puniyu'
description: '设置Rust作'
branding:
  icon: activity
  color: purple

inputs:
  toolchain:
    description: Rust toolchain specification
    required: false
  components:
    required: false
    type: string
    description: space separated Rust components
  target:
    required: false
    type: string
    description: target triple to install
  tools:
    required: false
    type: string
    description: comma separated Cargo tools
  save-cache:
    default: false
    required: false
    type: boolean
    description: whether to save cache
  prefix-key:
    required: false
    type: string
    description: cache key prefix

runs:
  using: 'composite'
  steps:
    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@1.91.0

    - name: Check File
      id: check_file
      shell: bash
      run: |
        if [ -f "rust-toolchain.toml" ]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Change to minimal profile
      uses: colt-1/toml-editor@1.1.1
      if: steps.check_file.outputs.exists == 'true'
      with:
        file: rust-toolchain.toml
        key: toolchain.profile
        value: minimal

    - name: Set Minimal Profile
      shell: bash
      if: steps.check_file.outputs.exists == 'true'
      run: rustup set profile minimal

    - name: Add Target
      shell: bash
      if: ${{ inputs.target }}
      run: rustup target add ${{ inputs.target }}

    - name: Add Components
      shell: bash
      if: ${{ inputs.components }}
      run: rustup component add ${{ inputs.components }}

    - name: Install Tools
      uses: taiki-e/install-action@v2
      if: ${{ inputs.tools }}
      with:
        tool: ${{ inputs.tools }}

    - name: Cache
      uses: Swatinem/rust-cache@v2
      if: ${{ inputs.save-cache == 'true' }}
      with:
        prefix-key: ${{ inputs.prefix-key || '' }}
        save-if: ${{ inputs.save-cache == 'true' }}